import Footer from "@/components/Footer";
import Banner from "@/views/home/Banner";
import Different from "@/views/home/Different";
import Guard from "@/views/home/Guard";
import Landing from "@/views/home/Landing";
import LocationMap from "@/views/home/LocationMap";
import Panel from "@/views/home/Panel";
import Trust from "@/views/home/Trust";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-red relative z-10 flex flex-col items-center justify-center overflow-hidden bg-primary-bg">
        {/* <div className="absolute  top-[-300px] h-full max-h-[870px] w-full bg-spot bg-cover" /> */}
        <svg
          viewBox="0 0 1543 870"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="absolute  top-[-420px] h-[870px] w-[1543px]"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1540.29 447.996C1515.7 596.089 1215.04 624.18 1024.76 705.892C870.658 772.069 745.117 879.87 561.436 868.351C353.361 855.302 166.332 767.947 71.3029 646.1C-26.4022 520.822 -20.2874 371.048 75.5728 245.374C169.997 121.582 350.231 35.653 557.693 8.43465C759.175 -17.9992 954.257 31.8553 1124.06 107.816C1316.89 194.075 1565.49 296.242 1540.29 447.996Z"
            fill="#00222E"
            stroke="black"
          />
        </svg>
        <Landing />
        <Banner />
        <Different />
        <Trust />
        <LocationMap />
        <Guard />
        <Panel />
        <Footer />
      </main>
    </>
  );
};

export default Home;
