import Navbar from "@/components/Navbar";
import { type NextPage } from "next";
import Head from "next/head";

const Servers: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-red flex min-h-screen flex-col items-center justify-center"></main>
    </>
  );
};

export default Servers;
